### PR TITLE
Add bot-discord template

### PR DESCRIPTION
**Pull request by TheoryOfNekomata**
The new template can be used to create Discord bots.

### CODE REVIEW

**Review by LXSMNSYC — APPROVED** [review]
Looks good! Just needed to know if `dotenv` is really needed on runtime since pridepack already inlines the `.env` files during compile-time.

**Comment by TheoryOfNekomata** [comment]
> Looks good! Just needed to know if `dotenv` is really needed on runtime since pridepack already inlines the `.env` files during compile-time.

`dotenv` is only required for setting up the bot token from Discord, as well as the intents the bot needs to access Discord functions.

**Comment by TheoryOfNekomata** [comment]
Updates with this PR? Need to change things?

**Comment by LXSMNSYC** [comment]
> Updates with this PR? Need to change things?

Everything's good, I'll merge it with the internal changes

**Pull request merged**
